spin_manifest_version = "1"
authors = ["Gordon Smith <GordonJSmith@gmail.com>"]
description = ""
name = "docker-app"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "docker-app"
source = "main.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
executor = { type = "wagi" }
[component.build]
command = "zig build-exe -O ReleaseSmall -target wasm32-wasi main.c -lc"
watch = ["**/*.c"]
