spin_manifest_version = "1"
authors = ["Gordon Smith <GordonJSmith@gmail.com>"]
description = ""
name = "spin-ts"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-ts"
source = "target/spin-ts.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
