spin_manifest_version = "1"
authors = ["Gordon Smith <GordonJSmith@gmail.com>"]
description = ""
name = "spin-docker-python"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-docker-python"
source = "app.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "Pipfile"]
