/* 
interface iterator {
  record row {
    value: string,
    done: bool,
  }

  next: func() -> row
}
*/

interface host {
  print: func(msg: string)
}

default world test {
  import global: self.host

  export echo: func(msg: string) -> string
  export add: func(a: u32, b:u32) -> u32
  export sub: func(a: u32, b:u32) -> u32
}
